const string = {
    Home: 'Home',
    Dashboard:'Dashboard',
    Product_management : 'Product Management',
    Don_hang: 'Đơn hàng thứ: ',
    ListProduct: 'Danh sách sản phẩm',
    Product:'Product',
    Cart: 'Cart',
    YourCart: 'Giỏ hàng của bạn',
    Address: 'Địa chỉ nhận hàng',
    LoginSuccess: 'Đăng nhập thành công',
    InforUser: 'Thông tin tài khoản',
    ChooseProduct: 'Chọn thêm sản phẩm',
    TotalPay: 'Tổng thanh toán: ',
    InforAddress: 'Địa chỉ:',
    SeeBill: 'Xem hóa đơn',
    ConfirmOrder: 'Xác nhận đơn hàng',
    LoginWithAccount: 'Đăng nhập vào tài khoản',
    SignInWith: 'Sign in with',
    ShowPassword: 'Show password',
    ForgotPassword: 'Forgot password?',
    Login: 'Login',
    NoAccount: `Don't have an account?`,
    Register: 'Register',
    AddnewProduct: 'Thêm sản phẩm mới',
    CreateProduct: 'Tạo sản phẩm mới',
    UploadImage: 'Tải ảnh',
}
export default string